#!/bin/sh


# case $INPUT_STRING in
# 	hello)
# 		echo "Hello yourself!"
# 		;;
# 	bye)
# 		echo "See you again!"
# 		break
# 		;;
# 	*)

for file in ./* ;do
	case $file in
		*.sh) continue ;;
		*.json) continue ;;
	esac
	if [ -d $file ] ; then 
		echo "是个目录"
		cd $file
		for subFileDir in ./* ;do
			imageName=`echo ${subFileDir} | awk -F./ '{ print $2 }' | cut -d '.' -f 1`
			echo "\033[34m 内层目录 $imageName \033[0m"
			imageDir=$imageName.imageset
			echo "\033[32m 处理 $imageName \033[0m"
			mkdir $imageDir && mv $subFileDir $imageDir
			echo { >> Contents.json
			echo "\"images\":[" >> Contents.json
			echo "{\n\t"\"idiom\":"\"iphone\",\n\t"\"filename\":"\"${imageName}.png\",\n\t"\"scale\":"\"3x\" \n}">> Contents.json
			echo "]," >> Contents.json
			echo "\"info\":{
			"\"version\"":1,
			"\"author\"":"\"xcode\""
			}">>Contents.json
			echo }>>Contents.json
			mv Contents.json $imageDir
		done
		cd ..
	else
		imageName=`echo ${file} | awk -F./ '{ print $2 }' | cut -d '.' -f 1`
		imageDir=$imageName.imageset
		echo "\033[32m 处理 $imageName \033[0m"
		mkdir $imageDir && mv $file $imageDir
		echo { >> Contents.json
		echo "\"images\":[" >> Contents.json
		echo "{\n\t"\"idiom\":"\"iphone\",\n\t"\"filename\":"\"${imageName}.png\",\n\t"\"scale\":"\"3x\" \n}">> Contents.json
		echo "]," >> Contents.json
		echo "\"info\":{
		"\"version\"":1,
		"\"author\"":"\"xcode\""
		}">>Contents.json
		echo }>>Contents.json
		mv Contents.json $imageDir
		echo 
	fi
done

echo {>>Contents.json
echo "\"info\" : {
    "\"version\"" : 1 ,
    "\"author\"" : "\"xcode\""
  }">>Contents.json
echo }>>Contents.json

echo "\033[32m 完成 \033[0m"


# echo ./shishicai/shiyixuanwuopen_9.png | awk -F./ '{ print $2 }' | cut -d '.' -f 1